filegroup(
  name = "e2e",
  srcs = [
    "//lib/tests:core",
#    "//tests:qrpc"
  ],
  visibility = ["//visibility:public"],
)

filegroup(
  name = "core",
  srcs = [
    "//lib/tests/e2e/core/server:e2e_server",
    "//lib/tests/e2e/core/client:e2e_client_native",
  ]
)